# fly.toml app configuration file generated for urupix-wuzapi on 2026-08-03T13:30:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'urupix-wuzapi'
primary_region = 'gru'
kill_signal = 'SIGINT'
kill_timeout = '30s'
swap_size_mb = 512

[build]
  dockerfile = 'Dockerfile'

[env]
  SESSION_DEVICE_NAME = 'Urupix WhatsApp'
  TZ = 'America/Sao_Paulo'
  WEBHOOK_FORMAT = 'json'
  WUZAPI_PORT = '8080'

[[mounts]]
  source = 'wuzapi_data'
  destination = '/app/dbdata'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [[http_service.checks]]
    interval = '30s'
    timeout = '5s'
    grace_period = '10s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '512mb'
